version: '3'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    command: --innodb_use_native_aio=0
    platform: linux/x86_64
    image: mysql:5.7
    container_name: pinder-mysql
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pinder
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php

  redis:
    image: redis:7.2
    container_name: pinder_redis
    ports:
      - "6382:6379"
